name: brisk

services:
  backend:
    build: 
      context: ./backend
    container_name: brisk-backend
    image: brisk-backend:latest
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///app/data/brisk.db
    volumes:
      - sqlite_data:/app/data
    networks:
      - brisk-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    container_name: brisk-frontend
    image: brisk-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - brisk-network
    restart: unless-stopped
    env_file:
      - ./frontend/.env

volumes:
  sqlite_data:
    driver: local

networks:
  brisk-network:
    driver: bridge
